### ISSUE TITLE
Missing proj_api.h

### ISSUE THREAD

**Issue by whossname** [CandyGumdrop/proj#2]
When trying to build this library with make I got the following error:

```
cc -fPIC -Isrc -std=c99 -pedantic -Wall -Wextra -Wno-unused-parameter -c src/proj_nif.c -o src/proj_nif.o -I/usr/lib/erlang/erts-10.2.3/include
src/proj_nif.c:3:22: fatal error: proj_api.h: No such file or directory
compilation terminated.
Makefile:23: recipe for target 'src/proj_nif.o' failed
make: *** [src/proj_nif.o] Error 1
```

**Comment by CandyGumdrop** [comment]
Hi.  Which operating system are you building this on?  Do you have the PROJ.4 development package installed? (`libproj-dev` on Debian / Ubuntu, `proj-devel` on Fedora / RHEL / CentOS.)

**Comment by whossname** [comment]
I installed `proj-bin` on Ubuntu 16.04. Is that not going to work? I've already decided to use a different solution, so don't spend any time on this if it's not necessary.

**Comment by CandyGumdrop** [comment]
`proj-bin` on Ubuntu only provides the `proj` command-line utility and doesn't include the files necessary for compiling programs which use PROJ.4.  If you `apt install libproj-dev`, then it should work.

**Comment by CandyGumdrop** [comment]
I have updated the docs to clarify this.
